# -*- coding: utf-8 -*-
"""
Transfers API Flow Tests (GENERATED)

测试 transfers 模块的 API 端点，覆盖 Happy Path、参数校验、权限验证、
状态机流转、错误码返回等场景。

SoT References:
- docs/2.sot/STATE_MACHINE.md v2.6 第 12 章 (transfer_requests 状态机)
- docs/2.sot/API_SOT.md v9.0 (迁移相关端点)
- docs/2.sot/ERROR_CODES_SOT.md v2.1 (错误码定义)
- docs/2.sot/DATA_SCHEMA.md v5.2 (transfer_requests 表)

Generated by: ai-ad-api-automation-test Skill v1.3
Updated: 2025-12-02 (transfers-batch-v2 OpenSpec change)
Target: backend/tests/api/test_transfers_flow_generated.py
"""

import pytest
from datetime import date, timedelta
from decimal import Decimal
from uuid import uuid4

from backend.tests.common.state_asserts import (
    assert_state_transition_valid,
)


# ============================================================================
# API 端点常量
# SoT Ref: API_SOT.md v9.0 第 2.1 节 (路由前缀 /api/v1)
# ============================================================================

API_BASE = "/api/v1"
TRANSFERS_URL = f"{API_BASE}/transfers"


def transfer_url(transfer_id: int) -> str:
    """生成迁移详情 URL"""
    return f"{TRANSFERS_URL}/{transfer_id}"


def transfer_action_url(transfer_id: int, action: str) -> str:
    """生成迁移动作 URL"""
    return f"{TRANSFERS_URL}/{transfer_id}/{action}"


# ============================================================================
# Happy Path Tests - 成功流程测试
# ============================================================================

@pytest.mark.api
class TestTransfersHappyPath:
    """
    Happy Path: 完整成功流程测试

    SoT Reference: STATE_MACHINE.md v2.6 第 12 章
    覆盖流程: draft → pending_approval → approved → completed
    """

    def test_create_transfer_request__returns_201_and_draft(
        self, client, account_manager_headers, funded_ad_account, funded_ad_account_2
    ):
        """
        成功创建迁移申请 - 返回 201 且状态为 draft

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        """
        request_data = {
            "source_ad_account_id": funded_ad_account.id,
            "target_ad_account_id": funded_ad_account_2.id,
            "transfer_amount": "1000.00",
            "reason": "死号余额迁移",
        }

        response = client.post(
            TRANSFERS_URL,
            json=request_data,
            headers=account_manager_headers,
        )

        assert response.status_code == 201, f"Expected 201, got {response.status_code}: {response.text}"
        data = response.json()
        assert data["success"] is True
        assert data["data"]["status"] == "draft"
        assert data["data"]["transfer_amount"] == "1000.00"

    def test_submit_transfer_request__returns_200_and_pending_approval(
        self, client, account_manager_headers, funded_ad_account, funded_ad_account_2
    ):
        """
        成功提交迁移申请 - 返回 200 且状态为 pending_approval

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        状态流转: draft → pending_approval
        """
        # 先创建迁移申请
        create_response = client.post(
            TRANSFERS_URL,
            json={
                "source_ad_account_id": funded_ad_account.id,
                "target_ad_account_id": funded_ad_account_2.id,
                "transfer_amount": "1000.00",
                "reason": "测试提交",
            },
            headers=account_manager_headers,
        )
        assert create_response.status_code == 201
        transfer_id = create_response.json()["data"]["id"]

        # Act - 提交审批
        response = client.post(
            transfer_action_url(transfer_id, "submit"),
            json={},
            headers=account_manager_headers,
        )

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert data["data"]["status"] == "pending_approval"

    def test_approve_transfer_request__returns_200_and_approved(
        self, client, account_manager_headers, finance_headers, funded_ad_account, funded_ad_account_2
    ):
        """
        成功审批迁移申请 - 返回 200 且状态为 approved

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        状态流转: pending_approval → approved
        """
        # 创建并提交
        create_response = client.post(
            TRANSFERS_URL,
            json={
                "source_ad_account_id": funded_ad_account.id,
                "target_ad_account_id": funded_ad_account_2.id,
                "transfer_amount": "1000.00",
                "reason": "测试审批",
            },
            headers=account_manager_headers,
        )
        transfer_id = create_response.json()["data"]["id"]

        submit_response = client.post(
            transfer_action_url(transfer_id, "submit"),
            json={},
            headers=account_manager_headers,
        )
        assert submit_response.json()["data"]["status"] == "pending_approval"

        # Act - 审批
        response = client.post(
            transfer_action_url(transfer_id, "approve"),
            json={"approval_notes": "审批通过"},
            headers=finance_headers,
        )

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert data["data"]["status"] == "approved"

    def test_complete_transfer_request__returns_200_and_completed(
        self, client, account_manager_headers, finance_headers, admin_headers,
        funded_ad_account, funded_ad_account_2
    ):
        """
        成功完成迁移 - 返回 200 且状态为 completed

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        状态流转: approved → completed
        """
        # 创建、提交、审批
        create_response = client.post(
            TRANSFERS_URL,
            json={
                "source_ad_account_id": funded_ad_account.id,
                "target_ad_account_id": funded_ad_account_2.id,
                "transfer_amount": "1000.00",
                "reason": "测试完成",
            },
            headers=account_manager_headers,
        )
        transfer_id = create_response.json()["data"]["id"]

        client.post(
            transfer_action_url(transfer_id, "submit"),
            json={},
            headers=account_manager_headers,
        )

        client.post(
            transfer_action_url(transfer_id, "approve"),
            json={"approval_notes": "审批通过"},
            headers=finance_headers,
        )

        # Act - 完成迁移
        response = client.post(
            transfer_action_url(transfer_id, "complete"),
            json={},
            headers=admin_headers,
        )

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert data["data"]["status"] == "completed"

    def test_complete_transfer_flow__draft_to_completed(
        self, client, account_manager_headers, finance_headers, admin_headers,
        funded_ad_account, funded_ad_account_2
    ):
        """
        完整流程: 创建 → 提交 → 审批 → 完成

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        """
        # Step 1: 创建迁移申请
        create_response = client.post(
            TRANSFERS_URL,
            json={
                "source_ad_account_id": funded_ad_account.id,
                "target_ad_account_id": funded_ad_account_2.id,
                "transfer_amount": "1000.00",
                "reason": "完整流程测试",
            },
            headers=account_manager_headers,
        )
        assert create_response.status_code == 201
        transfer_id = create_response.json()["data"]["id"]

        # Step 2: 提交审批
        submit_response = client.post(
            transfer_action_url(transfer_id, "submit"),
            json={},
            headers=account_manager_headers,
        )
        assert submit_response.status_code == 200
        assert submit_response.json()["data"]["status"] == "pending_approval"

        # Step 3: 审批通过
        approve_response = client.post(
            transfer_action_url(transfer_id, "approve"),
            json={"approval_notes": "审批通过"},
            headers=finance_headers,
        )
        assert approve_response.status_code == 200
        assert approve_response.json()["data"]["status"] == "approved"

        # Step 4: 完成迁移
        complete_response = client.post(
            transfer_action_url(transfer_id, "complete"),
            json={},
            headers=admin_headers,
        )
        assert complete_response.status_code == 200
        assert complete_response.json()["data"]["status"] == "completed"


# ============================================================================
# Validation Tests - 参数校验测试
# ============================================================================

@pytest.mark.api
class TestTransfersValidation:
    """
    参数校验测试

    SoT Reference: ERROR_CODES_SOT.md v2.1 VALIDATION_ 类
    """

    def test_create_with_negative_amount__returns_422_validation_error(
        self, client, account_manager_headers, test_ad_account, test_ad_account_2
    ):
        """
        创建迁移申请时金额为负数 - 返回 422 (Pydantic validation)

        SoT Ref: ERROR_CODES_SOT.md v2.1 VALIDATION_ 类
        """
        request_data = {
            "source_ad_account_id": test_ad_account.id,
            "target_ad_account_id": test_ad_account_2.id,
            "transfer_amount": "-1000.00",
            "reason": "测试",
        }

        response = client.post(
            TRANSFERS_URL,
            json=request_data,
            headers=account_manager_headers,
        )

        # Pydantic v2 returns 422 for validation errors
        assert response.status_code == 422

    def test_create_with_same_account__returns_422_validation_error(
        self, client, account_manager_headers, test_ad_account
    ):
        """
        创建迁移申请时源账户和目标账户相同 - 返回 422 (model_validator)

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章 (业务约束)
        """
        request_data = {
            "source_ad_account_id": test_ad_account.id,
            "target_ad_account_id": test_ad_account.id,  # 相同账户
            "transfer_amount": "1000.00",
            "reason": "测试",
        }

        response = client.post(
            TRANSFERS_URL,
            json=request_data,
            headers=account_manager_headers,
        )

        # Pydantic model_validator returns 422
        assert response.status_code == 422

    def test_create_with_insufficient_balance__returns_400_biz_error(
        self, client, account_manager_headers, test_ad_account, test_ad_account_2
    ):
        """
        创建迁移申请时金额超过源账户余额 - 返回 400 + BIZ_ 错误码

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章 (迁移金额不得超过源账户余额)
        """
        request_data = {
            "source_ad_account_id": test_ad_account.id,
            "target_ad_account_id": test_ad_account_2.id,
            "transfer_amount": "10000000.00",  # 超过余额
            "reason": "测试",
        }

        response = client.post(
            TRANSFERS_URL,
            json=request_data,
            headers=account_manager_headers,
        )

        # Business logic error returns 400
        assert response.status_code == 400
        data = response.json()
        error = data.get("error", {})
        assert "BIZ" in error.get("code", "") or "balance" in error.get("message", "").lower()


# ============================================================================
# Permissions Tests - 权限验证测试
# ============================================================================

@pytest.mark.api
class TestTransfersPermissions:
    """
    权限验证测试

    SoT Reference: STATE_MACHINE.md v2.6 第 12 章 (角色权限)
    """

    def test_create_as_media_buyer__returns_403(
        self, client, media_buyer_headers, test_ad_account, test_ad_account_2
    ):
        """
        media_buyer 角色无权创建迁移申请 - 返回 403

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章 (仅 account_manager, finance, admin)
        """
        request_data = {
            "source_ad_account_id": test_ad_account.id,
            "target_ad_account_id": test_ad_account_2.id,
            "transfer_amount": "1000.00",
            "reason": "测试",
        }

        response = client.post(
            TRANSFERS_URL,
            json=request_data,
            headers=media_buyer_headers,
        )

        assert response.status_code == 403

    def test_approve_as_account_manager__returns_403(
        self, client, account_manager_headers, funded_ad_account, funded_ad_account_2
    ):
        """
        account_manager 角色无权审批迁移申请 - 返回 403

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章 (仅 finance, admin)
        """
        # 先创建并提交迁移申请
        create_response = client.post(
            TRANSFERS_URL,
            json={
                "source_ad_account_id": funded_ad_account.id,
                "target_ad_account_id": funded_ad_account_2.id,
                "transfer_amount": "1000.00",
                "reason": "测试权限",
            },
            headers=account_manager_headers,
        )
        transfer_id = create_response.json()["data"]["id"]

        client.post(
            transfer_action_url(transfer_id, "submit"),
            json={},
            headers=account_manager_headers,
        )

        # Act - account_manager 尝试审批（应该被拒绝）
        response = client.post(
            transfer_action_url(transfer_id, "approve"),
            json={"approval_notes": "测试"},
            headers=account_manager_headers,
        )

        assert response.status_code == 403

    def test_complete_as_finance__returns_403(
        self, client, account_manager_headers, finance_headers, funded_ad_account, funded_ad_account_2
    ):
        """
        finance 角色无权完成迁移 - 返回 403

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章 (仅 admin)
        """
        # 先创建、提交、审批迁移申请
        create_response = client.post(
            TRANSFERS_URL,
            json={
                "source_ad_account_id": funded_ad_account.id,
                "target_ad_account_id": funded_ad_account_2.id,
                "transfer_amount": "1000.00",
                "reason": "测试权限",
            },
            headers=account_manager_headers,
        )
        transfer_id = create_response.json()["data"]["id"]

        client.post(
            transfer_action_url(transfer_id, "submit"),
            json={},
            headers=account_manager_headers,
        )

        client.post(
            transfer_action_url(transfer_id, "approve"),
            json={"approval_notes": "审批通过"},
            headers=finance_headers,
        )

        # Act - finance 尝试完成（应该被拒绝）
        response = client.post(
            transfer_action_url(transfer_id, "complete"),
            json={},
            headers=finance_headers,
        )

        assert response.status_code == 403


# ============================================================================
# Error Code Tests - 错误码验证测试
# ============================================================================

@pytest.mark.api
class TestTransfersErrorCodes:
    """
    错误码返回验证测试

    SoT Reference: ERROR_CODES_SOT.md v2.1
    """

    def test_get_nonexistent_transfer__returns_404_biz_002(
        self, client, account_manager_headers
    ):
        """
        查询不存在的迁移申请 - 返回 404 + BIZ_002

        SoT Ref: ERROR_CODES_SOT.md v2.1 BIZ_002 (资源不存在)
        """
        response = client.get(
            transfer_url(99999999),
            headers=account_manager_headers,
        )

        assert response.status_code == 404
        data = response.json()
        error = data.get("error", {})
        assert error.get("code") == "BIZ_002" or "not found" in error.get("message", "").lower()

    def test_approve_nonexistent_transfer__returns_404_biz_002(
        self, client, finance_headers
    ):
        """
        审批不存在的迁移申请 - 返回 404 + BIZ_002

        SoT Ref: ERROR_CODES_SOT.md v2.1 BIZ_002 (资源不存在)
        """
        response = client.post(
            transfer_action_url(99999999, "approve"),
            json={"approval_notes": "测试"},
            headers=finance_headers,
        )

        assert response.status_code == 404
        data = response.json()
        error = data.get("error", {})
        assert error.get("code") == "BIZ_002" or "not found" in error.get("message", "").lower()

    def test_complete_with_invalid_state__returns_409_state_error(
        self, client, account_manager_headers, admin_headers, funded_ad_account, funded_ad_account_2
    ):
        """
        在非 approved 状态下完成迁移 - 返回 409 + STATE_ 错误码

        SoT Ref: ERROR_CODES_SOT.md v2.1 STATE_ 类 (状态流转错误)
        """
        # Arrange - 创建迁移申请（draft 状态，不能直接完成）
        create_response = client.post(
            TRANSFERS_URL,
            json={
                "source_ad_account_id": funded_ad_account.id,
                "target_ad_account_id": funded_ad_account_2.id,
                "transfer_amount": "1000.00",
                "reason": "测试状态",
            },
            headers=account_manager_headers,
        )
        transfer_id = create_response.json()["data"]["id"]
        # 不提交和审批，保持 draft 状态

        # Act - 尝试在 draft 状态下完成（应该被拒绝）
        response = client.post(
            transfer_action_url(transfer_id, "complete"),
            json={},
            headers=admin_headers,
        )

        # Assert
        assert response.status_code == 409
        data = response.json()
        error = data.get("error", {})
        assert "STATE" in error.get("code", "") or "state" in error.get("message", "").lower()


# ============================================================================
# State Machine Tests - 状态机流转测试
# ============================================================================

@pytest.mark.api
class TestTransfersStateMachine:
    """
    状态机流转测试

    SoT Reference: STATE_MACHINE.md v2.6 第 12 章
    """

    def test_valid_transition__draft_to_pending_approval(self):
        """
        合法流转: draft → pending_approval

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        """
        assert_state_transition_valid("transfer_requests", "draft", "pending_approval")

    def test_valid_transition__pending_approval_to_approved(self):
        """
        合法流转: pending_approval → approved

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        """
        assert_state_transition_valid("transfer_requests", "pending_approval", "approved")

    def test_valid_transition__pending_approval_to_rejected(self):
        """
        合法流转: pending_approval → rejected

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        """
        assert_state_transition_valid("transfer_requests", "pending_approval", "rejected")

    def test_valid_transition__approved_to_completed(self):
        """
        合法流转: approved → completed

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        """
        assert_state_transition_valid("transfer_requests", "approved", "completed")

    def test_invalid_transition__draft_to_completed(self):
        """
        非法流转: draft 不能直接到 completed

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章 (必须先到 pending_approval)
        """
        valid_targets = ["pending_approval", "rejected"]
        assert "completed" not in valid_targets

    def test_invalid_transition__rejected_to_approved(self):
        """
        非法流转: rejected 不能到 approved（rejected 是终态）

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        """
        valid_targets = []  # rejected 是终态
        assert "approved" not in valid_targets

    def test_illegal_transition__completed_to_approved(
        self, client, account_manager_headers, finance_headers, admin_headers,
        funded_ad_account, funded_ad_account_2
    ):
        """
        非法流转: completed 不能回退到 approved（completed 是终态）

        SoT Ref: STATE_MACHINE.md v2.6 第 12 章
        """
        # Arrange - 先完成迁移流程，到达 completed 状态
        create_response = client.post(
            TRANSFERS_URL,
            json={
                "source_ad_account_id": funded_ad_account.id,
                "target_ad_account_id": funded_ad_account_2.id,
                "transfer_amount": "1000.00",
                "reason": "测试回退",
            },
            headers=account_manager_headers,
        )
        transfer_id = create_response.json()["data"]["id"]

        client.post(transfer_action_url(transfer_id, "submit"), json={}, headers=account_manager_headers)
        client.post(transfer_action_url(transfer_id, "approve"), json={"approval_notes": "审批"}, headers=finance_headers)
        client.post(transfer_action_url(transfer_id, "complete"), json={}, headers=admin_headers)

        # Act - 尝试回退（API 不存在）
        response = client.post(
            transfer_action_url(transfer_id, "revert"),
            json={},
            headers=admin_headers,
        )

        # Assert - 应该返回 404 (API 不存在) 或 405 (Method Not Allowed)
        assert response.status_code in [404, 405, 409]
