# -*- coding: utf-8 -*-
"""
Trend Risk API Flow Tests (GENERATED)

测试 trend_risk 模块的 API 端点，覆盖 Happy Path、参数校验、权限验证、
状态机流转、错误码返回等场景。

SoT References:
- docs/2.sot/STATE_MACHINE.md v2.6 第 8 章 (daily_reports 状态机中的 trend 相关状态)
- docs/2.sot/API_SOT.md v9.0 第 9.3-9.4 节 (Trend Flag/Resolve API)
- docs/2.sot/ERROR_CODES_SOT.md v2.1 第 4.7 节 (TREND_ 错误码)
- docs/2.sot/DATA_SCHEMA.md v5.2 第 3.3.1 节 (daily_reports 表)

Generated by: ai-ad-api-automation-test Skill v1.3
Target: backend/tests/api/test_trend_risk_flow_generated.py
"""

import pytest
from datetime import date, timedelta
from decimal import Decimal

from backend.models import DailyReport
from backend.models.base import DailyReportStatus
from backend.tests.common.state_asserts import (
    assert_daily_report_state,
    assert_state_transition_valid,
)


# ============================================================================
# API 端点常量
# SoT Ref: API_SOT.md v9.0 第 2.1 节 (路由前缀 /api/v1)
# ============================================================================

API_BASE = "/api/v1"
DAILY_REPORTS_URL = f"{API_BASE}/daily-reports"


def trend_flag_url(report_id: int) -> str:
    """生成趋势标记 URL"""
    return f"{DAILY_REPORTS_URL}/{report_id}/trend-flag"


def trend_resolve_url(report_id: int) -> str:
    """生成趋势解决 URL"""
    return f"{DAILY_REPORTS_URL}/{report_id}/trend-resolve"


# ============================================================================
# Happy Path Tests - 成功流程测试
# ============================================================================

@pytest.mark.api
class TestTrendRiskHappyPath:
    """
    Happy Path: 完整成功流程测试

    SoT Reference: STATE_MACHINE.md v2.6 第 8 章
    覆盖流程: trend_pending → trend_flagged → trend_resolved
    """

    def test_flag_trend_anomaly__returns_200_and_trend_flagged(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        成功标记趋势异常 - 返回 200 且状态为 trend_flagged

        SoT Ref: API_SOT.md v9.0 第 9.3 节
        状态流转: trend_pending → trend_flagged
        """
        # Arrange - 创建一个处于 trend_pending 状态的日报
        report = DailyReport(
            id=1,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_PENDING.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        request_data = {
            "audit_notes": "检测到粉数骤降，需要人工复核",
        }

        # Act
        response = client.post(
            trend_flag_url(report.id),
            json=request_data,
            headers=data_operator_headers,
        )

        # Assert
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert data["success"] is True
        assert data["data"]["status"] == "trend_flagged"
        assert "trend_flag_reason" in data["data"] or data["data"].get("trend_flag") == "flagged"

    def test_resolve_trend_anomaly__returns_200_and_trend_resolved(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        成功解决趋势异常 - 返回 200 且状态为 trend_resolved

        SoT Ref: API_SOT.md v9.0 第 9.4 节
        状态流转: trend_flagged → trend_resolved
        """
        # Arrange - 创建一个处于 trend_flagged 状态的日报
        report = DailyReport(
            id=2,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_FLAGGED.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
            trend_flag="flagged",
            trend_flag_reason="TF-001: 粉数骤降50%",
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        request_data = {
            "audit_notes": "已核实，数据正常，解除标记",
        }

        # Act
        response = client.post(
            trend_resolve_url(report.id),
            json=request_data,
            headers=data_operator_headers,
        )

        # Assert
        assert response.status_code == 200, f"Expected 200, got {response.status_code}: {response.text}"
        data = response.json()
        assert data["success"] is True
        assert data["data"]["status"] == "trend_resolved"

    def test_complete_trend_risk_flow__flag_then_resolve(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        完整流程: 标记异常 → 解决异常

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        # Arrange - 创建 trend_pending 状态的日报
        report = DailyReport(
            id=3,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_PENDING.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Step 1: 标记异常
        flag_response = client.post(
            trend_flag_url(report.id),
            json={"audit_notes": "检测到异常"},
            headers=data_operator_headers,
        )
        assert flag_response.status_code == 200
        assert flag_response.json()["data"]["status"] == "trend_flagged"

        # Step 2: 解决异常
        resolve_response = client.post(
            trend_resolve_url(report.id),
            json={"audit_notes": "已解决"},
            headers=data_operator_headers,
        )
        assert resolve_response.status_code == 200
        assert resolve_response.json()["data"]["status"] == "trend_resolved"


# ============================================================================
# Validation Tests - 参数校验测试
# ============================================================================

@pytest.mark.api
class TestTrendRiskValidation:
    """
    参数校验测试

    SoT Reference: ERROR_CODES_SOT.md v2.1 VALIDATION_ 类
    """

    def test_flag_without_notes__returns_200_but_notes_optional(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        标记异常时 audit_notes 为可选字段

        SoT Ref: API_SOT.md v9.0 第 9.3 节
        """
        # Arrange
        report = DailyReport(
            id=4,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_PENDING.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        request_data = {}  # 不提供 audit_notes

        # Act
        response = client.post(
            trend_flag_url(report.id),
            json=request_data,
            headers=data_operator_headers,
        )

        # Assert - audit_notes 为可选，应该成功
        assert response.status_code in [200, 400]  # 取决于实现

    def test_resolve_without_notes__may_return_400_trend_010(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        解决异常时如果未填写 trend_resolution_note，可能返回 TREND_010

        SoT Ref: ERROR_CODES_SOT.md v2.1 TREND_010 (复核原因缺失)
        """
        # Arrange
        report = DailyReport(
            id=5,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_FLAGGED.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        request_data = {}  # 不提供 audit_notes

        # Act
        response = client.post(
            trend_resolve_url(report.id),
            json=request_data,
            headers=data_operator_headers,
        )

        # Assert - 取决于实现，可能要求必填
        # 如果实现要求必填，应返回 400 + TREND_010
        if response.status_code == 400:
            data = response.json()
            assert data.get("code") in ["TREND_010", "VALIDATION_001"]


# ============================================================================
# Permissions Tests - 权限验证测试
# ============================================================================

@pytest.mark.api
class TestTrendRiskPermissions:
    """
    权限验证测试

    SoT Reference: API_SOT.md v9.0 第 9.3-9.4 节 (角色要求: data_operator, admin)
    """

    def test_flag_as_media_buyer__returns_403(
        self, client, media_buyer_headers, test_ad_account, db_session
    ):
        """
        media_buyer 角色无权标记趋势异常 - 返回 403

        SoT Ref: API_SOT.md v9.0 第 9.3 节 (仅 data_operator, admin)
        """
        # Arrange
        report = DailyReport(
            id=4,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_PENDING.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_flag_url(report.id),
            json={"audit_notes": "测试"},
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 403, f"Expected 403, got {response.status_code}: {response.text}"

    def test_resolve_as_media_buyer__returns_403(
        self, client, media_buyer_headers, test_ad_account, db_session
    ):
        """
        media_buyer 角色无权解决趋势异常 - 返回 403

        SoT Ref: API_SOT.md v9.0 第 9.4 节 (仅 data_operator, admin)
        """
        # Arrange
        report = DailyReport(
            id=5,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_FLAGGED.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_resolve_url(report.id),
            json={"audit_notes": "测试"},
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 403

    def test_flag_as_admin__returns_200(
        self, client, admin_headers, test_ad_account, db_session
    ):
        """
        admin 角色可以标记趋势异常 - 返回 200

        SoT Ref: API_SOT.md v9.0 第 9.3 节
        """
        # Arrange
        report = DailyReport(
            id=4,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_PENDING.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_flag_url(report.id),
            json={"audit_notes": "管理员标记"},
            headers=admin_headers,
        )

        # Assert
        assert response.status_code == 200

    def test_resolve_as_admin__returns_200(
        self, client, admin_headers, test_ad_account, db_session
    ):
        """
        admin 角色可以解决趋势异常 - 返回 200

        SoT Ref: API_SOT.md v9.0 第 9.4 节
        """
        # Arrange
        report = DailyReport(
            id=5,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_FLAGGED.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_resolve_url(report.id),
            json={"audit_notes": "管理员解决"},
            headers=admin_headers,
        )

        # Assert
        assert response.status_code == 200


# ============================================================================
# Error Code Tests - 错误码验证测试
# ============================================================================

@pytest.mark.api
class TestTrendRiskErrorCodes:
    """
    错误码返回验证测试

    SoT Reference: ERROR_CODES_SOT.md v2.1 第 4.7 节 (TREND_ 错误码)
    """

    def test_flag_nonexistent_report__returns_404_biz_002(
        self, client, data_operator_headers
    ):
        """
        标记不存在的日报 - 返回 404 + BIZ_002

        SoT Ref: ERROR_CODES_SOT.md v2.1 BIZ_002 (资源不存在)
        """
        # Act
        response = client.post(
            trend_flag_url(99999999),
            json={"audit_notes": "测试"},
            headers=data_operator_headers,
        )

        # Assert
        assert response.status_code == 404
        data = response.json()
        assert data.get("success") is False
        error = data.get("error", {})
        assert error.get("code") == "BIZ_002"
        assert "not found" in error.get("message", "").lower() or "不存在" in error.get("message", "")

    def test_resolve_nonexistent_report__returns_404_biz_002(
        self, client, data_operator_headers
    ):
        """
        解决不存在的日报 - 返回 404 + BIZ_002

        SoT Ref: ERROR_CODES_SOT.md v2.1 BIZ_002 (资源不存在)
        """
        # Act
        response = client.post(
            trend_resolve_url(99999999),
            json={"audit_notes": "测试"},
            headers=data_operator_headers,
        )

        # Assert
        assert response.status_code == 404
        data = response.json()
        assert data.get("success") is False
        error = data.get("error", {})
        assert error.get("code") == "BIZ_002"
        assert "not found" in error.get("message", "").lower() or "不存在" in error.get("message", "")

    def test_flag_wrong_status__returns_400_trend_002(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        在非 trend_pending 状态下标记异常 - 返回 400 + TREND_002

        SoT Ref: ERROR_CODES_SOT.md v2.1 TREND_002 (风控复核未完成)
        """
        # Arrange - 创建 raw_submitted 状态的日报（不能直接标记）
        report = DailyReport(
            id=6,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.RAW_SUBMITTED.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_flag_url(report.id),
            json={"audit_notes": "测试"},
            headers=data_operator_headers,
        )

        # Assert - 应该返回状态错误
        assert response.status_code in [400, 409]
        # 可能返回 TREND_002 或其他状态机错误码

    def test_resolve_wrong_status__returns_400_trend_002(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        在非 trend_flagged 状态下解决异常 - 返回 400 + TREND_002

        SoT Ref: ERROR_CODES_SOT.md v2.1 TREND_002 (风控复核未完成)
        """
        # Arrange - 创建 trend_pending 状态的日报（不能直接解决）
        report = DailyReport(
            id=7,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_PENDING.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_resolve_url(report.id),
            json={"audit_notes": "测试"},
            headers=data_operator_headers,
        )

        # Assert - 应该返回状态错误
        assert response.status_code in [400, 409]
        # 可能返回 TREND_002 或其他状态机错误码


# ============================================================================
# State Machine Tests - 状态机流转测试
# ============================================================================

@pytest.mark.api
class TestTrendRiskStateMachine:
    """
    状态机流转测试

    SoT Reference: STATE_MACHINE.md v2.6 第 8 章
    """

    def test_valid_transition__trend_pending_to_trend_flagged(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        合法流转: trend_pending → trend_flagged

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        # Arrange
        report = DailyReport(
            id=4,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_PENDING.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_flag_url(report.id),
            json={"audit_notes": "标记异常"},
            headers=data_operator_headers,
        )

        # Assert
        assert response.status_code == 200
        assert response.json()["data"]["status"] == "trend_flagged"

    def test_valid_transition__trend_flagged_to_trend_resolved(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        合法流转: trend_flagged → trend_resolved

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        # Arrange
        report = DailyReport(
            id=5,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_FLAGGED.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_resolve_url(report.id),
            json={"audit_notes": "解决异常"},
            headers=data_operator_headers,
        )

        # Assert
        assert response.status_code == 200
        assert response.json()["data"]["status"] == "trend_resolved"

    def test_invalid_transition__raw_submitted_to_trend_flagged(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        非法流转: raw_submitted 不能直接到 trend_flagged

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节 (必须先到 trend_pending)
        """
        # Arrange
        report = DailyReport(
            id=10,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.RAW_SUBMITTED.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_flag_url(report.id),
            json={"audit_notes": "测试"},
            headers=data_operator_headers,
        )

        # Assert - 应该被拒绝
        assert response.status_code in [400, 409]

    def test_invalid_transition__trend_ok_to_trend_resolved(
        self, client, data_operator_headers, test_ad_account, db_session
    ):
        """
        非法流转: trend_ok 不能直接到 trend_resolved

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        # Arrange
        report = DailyReport(
            id=11,
            ad_account_id=test_ad_account.id,
            report_date=date.today(),
            status=DailyReportStatus.TREND_OK.value,
            conversions_raw=50,
            raw_spend=Decimal("100.00"),
        )
        db_session.add(report)
        db_session.commit()
        db_session.refresh(report)

        # Act
        response = client.post(
            trend_resolve_url(report.id),
            json={"audit_notes": "测试"},
            headers=data_operator_headers,
        )

        # Assert - 应该被拒绝
        assert response.status_code in [400, 409]

