# -*- coding: utf-8 -*-
"""
Daily Report API Flow Tests (GENERATED)

测试 daily_report 模块的 API 端点，覆盖 Happy Path、参数校验、权限验证、
状态机流转、错误码返回等场景。

SoT References:
- docs/sot/STATE_MACHINE.md v2.6 第 8 章 (粉数确认状态机)
- docs/sot/API_SOT.md v9.0 第 9 节 (Daily Reports API)
- docs/sot/ERROR_CODES_SOT.md v2.1 (错误码定义)
- docs/sot/DATA_SCHEMA.md v5.2 第 3.3.1 节 (daily_reports 表)

Generated by: ai-ad-api-automation-test Skill v1.2
Target: backend/tests/api/test_daily_report_flow_generated.py
"""

import pytest
from datetime import date, timedelta
from decimal import Decimal
from uuid import uuid4

from backend.tests.common.factories import create_test_daily_report
from backend.tests.common.state_asserts import (
    assert_daily_report_state,
    assert_state_transition_valid,
    DAILY_REPORT_STATES,
    DAILY_REPORT_TRANSITIONS,
    DAILY_REPORT_TERMINAL_STATES,
)
from backend.tests.common.error_helpers import (
    assert_error_code,
    assert_validation_error,
    assert_business_error,
)


# ============================================================================
# API 端点常量
# SoT Ref: API_SOT.md v9.0 第 2.1 节 (路由前缀 /api/v1)
# ============================================================================

API_BASE = "/api/v1"
DAILY_REPORTS_URL = f"{API_BASE}/daily-reports"


def daily_report_url(report_id: int) -> str:
    """生成日报详情 URL"""
    return f"{DAILY_REPORTS_URL}/{report_id}"


def daily_report_action_url(report_id: int, action: str) -> str:
    """生成日报动作 URL"""
    return f"{DAILY_REPORTS_URL}/{report_id}/{action}"


# ============================================================================
# Happy Path Tests - 成功流程测试
# ============================================================================

@pytest.mark.api
class TestDailyReportHappyPath:
    """
    Happy Path: 完整成功流程测试

    SoT Reference: STATE_MACHINE.md v2.6 第 8 章
    覆盖流程: raw_submitted → trend_pending → trend_ok → final_pending
              → final_confirmed → final_locked
    """

    def test_create_daily_report__returns_201_and_raw_submitted(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        成功创建日报 - 返回 201 且状态为 raw_submitted

        SoT Ref: API_SOT.md v9.0 第 9.2 节
        业务规则: BR-RPT-001 (日报提交约束)
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            "raw_spend": "5000.00",
            "impressions": 50000,
            "clicks": 1200,
            "notes": "测试日报提交",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 201, f"Expected 201, got {response.status_code}: {response.text}"
        data = response.json()
        assert data["success"] is True
        assert data["data"]["status"] == "raw_submitted"
        assert data["data"]["conversions_raw"] == 100
        assert data["data"]["raw_spend"] == "5000.00"

    def test_get_daily_report__returns_200_with_details(
        self, client, media_buyer_headers, test_daily_report
    ):
        """
        查询日报详情 - 返回 200 和完整信息

        SoT Ref: API_SOT.md v9.0 第 9.1 节
        """
        # Act
        response = client.get(
            daily_report_url(test_daily_report.id),
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert data["data"]["id"] == test_daily_report.id

    def test_list_daily_reports__returns_200_with_pagination(
        self, client, media_buyer_headers, test_daily_report
    ):
        """
        查询日报列表 - 返回 200 和分页数据

        SoT Ref: API_SOT.md v9.0 第 2.4 节 (分页规范)
        """
        # Act
        response = client.get(
            DAILY_REPORTS_URL,
            params={"page": 1, "page_size": 20},
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 200
        data = response.json()
        assert data["success"] is True
        assert "data" in data


# ============================================================================
# Validation Tests - 参数校验测试
# ============================================================================

@pytest.mark.api
class TestDailyReportValidation:
    """
    参数校验测试

    SoT Reference: ERROR_CODES_SOT.md v2.1 第 4.3 节 (VALIDATION_ 类)
    """

    def test_create_without_report_date__returns_400_validation_001(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        缺少必填字段 report_date - 返回 VALIDATION_001

        SoT Ref: ERROR_CODES_SOT.md v2.1 VALIDATION_001
        """
        # Arrange
        report_data = {
            # "report_date": missing
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 400 or response.status_code == 422

    def test_create_without_ad_account_id__returns_400_validation_001(
        self, client, media_buyer_headers
    ):
        """
        缺少必填字段 ad_account_id - 返回 VALIDATION_001

        SoT Ref: ERROR_CODES_SOT.md v2.1 VALIDATION_001
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            # "ad_account_id": missing
            "conversions_raw": 100,
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 400 or response.status_code == 422

    def test_create_without_conversions_raw__returns_400_validation_001(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        缺少必填字段 conversions_raw - 返回 VALIDATION_001

        SoT Ref: ERROR_CODES_SOT.md v2.1 VALIDATION_001
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": test_ad_account.id,
            # "conversions_raw": missing
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 400 or response.status_code == 422

    def test_create_without_raw_spend__returns_400_validation_001(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        缺少必填字段 raw_spend - 返回 VALIDATION_001

        SoT Ref: ERROR_CODES_SOT.md v2.1 VALIDATION_001
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            # "raw_spend": missing
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 400 or response.status_code == 422

    def test_create_with_negative_conversions__returns_400(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        非法参数: 粉数为负数 - 返回 400

        SoT Ref: API_SOT.md v9.0 第 9.2 节 (conversions_raw ≥0)
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": -10,  # 非法：负数
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 400 or response.status_code == 422

    def test_create_with_negative_spend__returns_400(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        非法参数: 消耗为负数 - 返回 400

        SoT Ref: API_SOT.md v9.0 第 9.2 节 (raw_spend ≥0)
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            "raw_spend": "-100.00",  # 非法：负数
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 400 or response.status_code == 422

    def test_create_with_future_date__returns_400_biz_201(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        非法参数: 日期为未来日期 - 返回 BIZ_201

        SoT Ref: ERROR_CODES_SOT.md v2.1 BIZ_201 (日期不能为未来)
        """
        # Arrange
        future_date = (date.today() + timedelta(days=1)).isoformat()
        report_data = {
            "report_date": future_date,  # 非法：未来日期
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 400
        data = response.json()
        # 期望错误码为 BIZ_201
        if "code" in data:
            assert data["code"] == "BIZ_201" or "日期" in data.get("message", "")

    def test_create_with_nonexistent_ad_account__returns_404_biz_002(
        self, client, media_buyer_headers
    ):
        """
        非法参数: 广告账户不存在 - 返回 BIZ_002

        SoT Ref: ERROR_CODES_SOT.md v2.1 BIZ_002 (资源不存在)
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": 99999999,  # 不存在的账户
            "conversions_raw": 100,
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code in [400, 404]


# ============================================================================
# Permission Tests - 权限验证测试
# ============================================================================

@pytest.mark.api
class TestDailyReportPermissions:
    """
    权限边界测试

    SoT Reference: AUTH_SPEC.md v2.0 第 3 节 (角色权限矩阵)
    SoT Reference: ERROR_CODES_SOT.md v2.1 AUTH_500 (权限不足)
    """

    def test_create_as_finance__returns_403_auth_500(
        self, client, finance_headers, test_ad_account
    ):
        """
        非 media_buyer 角色 (finance) 提交日报 - 返回 403

        SoT Ref: API_SOT.md v9.0 第 9.2 节 (允许角色: media_buyer)
        SoT Ref: ERROR_CODES_SOT.md v2.1 AUTH_500
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=finance_headers,
        )

        # Assert
        assert response.status_code == 403

    def test_create_as_data_operator__returns_403_auth_500(
        self, client, data_operator_headers, test_ad_account
    ):
        """
        非 media_buyer 角色 (data_operator) 提交日报 - 返回 403

        SoT Ref: API_SOT.md v9.0 第 9.2 节 (允许角色: media_buyer)
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=data_operator_headers,
        )

        # Assert
        assert response.status_code == 403

    def test_create_without_auth__returns_401(
        self, client, test_ad_account
    ):
        """
        无认证令牌 - 返回 401

        SoT Ref: ERROR_CODES_SOT.md v2.1 AUTH_400 (未提供认证令牌)
        """
        # Arrange
        report_data = {
            "report_date": date.today().isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            # headers: 不提供认证头
        )

        # Assert
        assert response.status_code == 401

    def test_trend_resolve_as_media_buyer__returns_403(
        self, client, media_buyer_headers, test_daily_report
    ):
        """
        media_buyer 角色执行趋势复核 - 返回 403

        SoT Ref: API_SOT.md v9.0 第 9.4 节 (允许角色: data_operator, admin)
        """
        # Arrange
        resolve_data = {
            "trend_resolution_note": "测试复核",
            "confirmed_normal": True,
        }

        # Act
        response = client.post(
            daily_report_action_url(test_daily_report.id, "trend-resolve"),
            json=resolve_data,
            headers=media_buyer_headers,
        )

        # Assert
        # 状态不对或权限不足都可能返回 4xx
        assert response.status_code in [400, 403]

    def test_real_spend_as_media_buyer__returns_403(
        self, client, media_buyer_headers, test_daily_report
    ):
        """
        media_buyer 角色录入 real_spend - 返回 403

        SoT Ref: API_SOT.md v9.0 第 9.5 节 (允许角色: data_operator, admin)
        """
        # Arrange
        spend_data = {
            "real_spend": "4800.00",
            "fee": "0.00",
        }

        # Act
        response = client.put(
            daily_report_action_url(test_daily_report.id, "real-spend"),
            json=spend_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code in [400, 403]


# ============================================================================
# State Machine Tests - 状态机流转测试
# ============================================================================

@pytest.mark.api
class TestDailyReportStateMachine:
    """
    状态机流转测试

    SoT Reference: STATE_MACHINE.md v2.6 第 8 章 (粉数确认状态机)
    8 状态: raw_submitted → trend_pending → trend_ok/trend_flagged
           → trend_resolved → final_pending → final_confirmed → final_locked
    """

    def test_state_enum_values__match_sot_definition(self):
        """
        验证状态枚举值与 SoT 定义一致

        SoT Ref: STATE_MACHINE.md v2.6 第 8.1 节
        """
        expected_states = {
            "raw_submitted",
            "trend_pending",
            "trend_ok",
            "trend_flagged",
            "trend_resolved",
            "final_pending",
            "final_confirmed",
            "final_locked",
        }
        assert DAILY_REPORT_STATES == expected_states

    def test_terminal_state__is_final_locked(self):
        """
        验证终态为 final_locked

        SoT Ref: STATE_MACHINE.md v2.6 第 8.1 节
        """
        assert DAILY_REPORT_TERMINAL_STATES == {"final_locked"}

    def test_valid_transition__raw_submitted_to_trend_pending(self):
        """
        合法流转: raw_submitted → trend_pending

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        assert_state_transition_valid("daily_report", "raw_submitted", "trend_pending")

    def test_valid_transition__trend_pending_to_trend_ok(self):
        """
        合法流转: trend_pending → trend_ok

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        assert_state_transition_valid("daily_report", "trend_pending", "trend_ok")

    def test_valid_transition__trend_pending_to_trend_flagged(self):
        """
        合法流转: trend_pending → trend_flagged

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        assert_state_transition_valid("daily_report", "trend_pending", "trend_flagged")

    def test_valid_transition__trend_ok_to_final_pending(self):
        """
        合法流转: trend_ok → final_pending

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        assert_state_transition_valid("daily_report", "trend_ok", "final_pending")

    def test_valid_transition__trend_flagged_to_trend_resolved(self):
        """
        合法流转: trend_flagged → trend_resolved

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节
        """
        assert_state_transition_valid("daily_report", "trend_flagged", "trend_resolved")

    def test_invalid_transition__raw_submitted_to_final_pending(self):
        """
        非法流转: raw_submitted 不能直接到 final_pending

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节 (流转白名单)
        """
        valid_targets = DAILY_REPORT_TRANSITIONS.get("raw_submitted", set())
        assert "final_pending" not in valid_targets

    def test_invalid_transition__trend_ok_to_final_locked(self):
        """
        非法流转: trend_ok 不能直接到 final_locked

        SoT Ref: STATE_MACHINE.md v2.6 第 8.2 节 (流转白名单)
        """
        valid_targets = DAILY_REPORT_TRANSITIONS.get("trend_ok", set())
        assert "final_locked" not in valid_targets

    def test_terminal_state__final_locked_has_no_transitions(self):
        """
        终态验证: final_locked 无后续流转

        SoT Ref: STATE_MACHINE.md v2.6 第 8.1 节 (终态)
        """
        valid_targets = DAILY_REPORT_TRANSITIONS.get("final_locked", set())
        assert valid_targets == set()


# ============================================================================
# Error Code Tests - 错误码验证测试
# ============================================================================

@pytest.mark.api
class TestDailyReportErrorCodes:
    """
    错误码返回验证测试

    SoT Reference: ERROR_CODES_SOT.md v2.1
    """

    def test_duplicate_report__returns_409_biz_003(
        self, client, media_buyer_headers, test_ad_account, test_daily_report
    ):
        """
        重复提交 (ad_account_id, report_date) - 返回 BIZ_003

        SoT Ref: ERROR_CODES_SOT.md v2.1 BIZ_003 (资源已存在)
        SoT Ref: API_SOT.md v9.0 第 9.2 节 (唯一键约束)
        """
        # Arrange - 使用已存在日报的 ad_account_id 和 report_date
        report_data = {
            "report_date": test_daily_report.report_date.isoformat(),
            "ad_account_id": test_daily_report.ad_account_id,
            "conversions_raw": 200,
            "raw_spend": "10000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 409

    def test_get_nonexistent_report__returns_404_biz_002(
        self, client, media_buyer_headers
    ):
        """
        查询不存在的日报 - 返回 BIZ_002

        SoT Ref: ERROR_CODES_SOT.md v2.1 BIZ_002 (资源不存在)
        """
        # Act
        response = client.get(
            daily_report_url(99999999),
            headers=media_buyer_headers,
        )

        # Assert
        assert response.status_code == 404


# ============================================================================
# Business Rule Tests - 业务规则测试
# ============================================================================

@pytest.mark.api
class TestDailyReportBusinessRules:
    """
    业务规则测试

    SoT Reference: BUSINESS_RULES.md v3.1 BR-RPT-001, BR-RPT-005
    """

    def test_create_report__initial_status_is_raw_submitted(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        新建日报初始状态为 raw_submitted

        SoT Ref: STATE_MACHINE.md v2.6 第 8.1 节
        业务规则: BR-RPT-001
        """
        # Arrange
        report_data = {
            "report_date": (date.today() - timedelta(days=1)).isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 50,
            "raw_spend": "2500.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        if response.status_code == 201:
            data = response.json()
            assert data["data"]["status"] == "raw_submitted"

    def test_create_report__conversions_final_defaults_to_zero(
        self, client, media_buyer_headers, test_ad_account
    ):
        """
        新建日报时 conversions_final 默认为 0

        SoT Ref: API_SOT.md v9.0 第 9.2 节 (Response Schema)
        """
        # Arrange
        report_data = {
            "report_date": (date.today() - timedelta(days=2)).isoformat(),
            "ad_account_id": test_ad_account.id,
            "conversions_raw": 100,
            "raw_spend": "5000.00",
        }

        # Act
        response = client.post(
            DAILY_REPORTS_URL,
            json=report_data,
            headers=media_buyer_headers,
        )

        # Assert
        if response.status_code == 201:
            data = response.json()
            # conversions_final 应为 0（未确认状态）
            assert data["data"].get("conversions_final", 0) == 0


# ============================================================================
# Integration Tests - 集成测试 (使用 common 工具函数)
# ============================================================================

@pytest.mark.api
class TestDailyReportIntegration:
    """
    集成测试 - 使用 common 工具函数验证

    使用 backend/tests/common 下的工厂函数和断言辅助函数
    """

    def test_factory_created_report__has_valid_state(self):
        """
        使用 factory 创建的日报数据状态合法

        使用: create_test_daily_report from factories.py
        字段对齐 SoT: raw_spend 为 raw 数据流消耗
        """
        # Act
        report_data = create_test_daily_report(
            status="raw_submitted",
            raw_spend=Decimal("100.00"),
        )

        # Assert
        assert report_data["status"] in DAILY_REPORT_STATES

    def test_factory_created_report__state_assertion_works(self):
        """
        使用 state_asserts 验证日报状态

        使用: assert_daily_report_state from state_asserts.py
        """
        # Arrange
        report_data = create_test_daily_report(status="trend_ok")

        # Act & Assert - 不应抛出异常
        assert_daily_report_state(report_data, "trend_ok")

    def test_state_transition_validation__rejects_invalid(self):
        """
        状态流转验证拒绝非法流转

        使用: assert_state_transition_valid from state_asserts.py
        """
        # raw_submitted → final_locked 是非法的
        with pytest.raises(AssertionError):
            assert_state_transition_valid(
                "daily_report",
                "raw_submitted",
                "final_locked"
            )
