# -*- coding: utf-8 -*-
"""
Finance Profit API Flow Tests (GENERATED)

测试 finance/profit 模块的 API 端点，覆盖 Happy Path、参数校验、权限验证、
错误码返回等场景。

SoT References:
- docs/2.sot/PROFIT_SOT.md v1.1 (利润报表 API 规范)
- docs/2.sot/API_SOT.md v9.0 (API 规范)
- docs/2.sot/ERROR_CODES_SOT.md v2.1 (错误码定义)
- docs/2.sot/DATA_SCHEMA.md v5.2 §3.6 (profit_aggregates/profit_report_snapshots 表)

Generated by: ai-ad-api-automation-test Skill v1.3
Generated: 2025-12-02 (finance-profit-v1 OpenSpec change)
Target: backend/tests/api/test_finance_profit_flow_generated.py
"""

import pytest
from datetime import date, timedelta
from decimal import Decimal
from uuid import uuid4


# ============================================================================
# API 端点常量
# SoT Ref: PROFIT_SOT.md v1.1 §3.1
# ============================================================================

API_BASE = "/api/v1"
PROFIT_URL = f"{API_BASE}/finance/profit"


def profit_generate_url() -> str:
    """生成利润聚合 URL"""
    return f"{PROFIT_URL}/generate"


def profit_monthly_url() -> str:
    """月度利润表 URL"""
    return f"{PROFIT_URL}/monthly"


def profit_daily_url() -> str:
    """日度利润数据 URL"""
    return f"{PROFIT_URL}/daily"


def profit_project_url(project_id: int) -> str:
    """项目利润明细 URL"""
    return f"{PROFIT_URL}/projects/{project_id}"


def profit_account_url(account_id: int) -> str:
    """账户消耗明细 URL"""
    return f"{PROFIT_URL}/accounts/{account_id}"


def profit_summary_url() -> str:
    """整体利润汇总 URL"""
    return f"{PROFIT_URL}/summary"


# ============================================================================
# Happy Path Tests - 成功流程测试
# ============================================================================

@pytest.mark.api
class TestFinanceProfitHappyPath:
    """
    Happy Path: 完整成功流程测试

    SoT Reference: PROFIT_SOT.md v1.1 §3
    覆盖 6 个 API 端点的成功场景
    """

    def test_generate_profit_aggregates__returns_200_and_summary(
        self, client, finance_headers, test_project
    ):
        """
        TC-PROFIT-HP-001: 成功生成月度聚合 - 返回 200 和摘要

        SoT Ref: PROFIT_SOT.md v1.1 §3.2
        """
        today = date.today()
        first_day = date(today.year, today.month, 1)
        # 上个月最后一天
        last_day = first_day - timedelta(days=1)
        first_of_last_month = date(last_day.year, last_day.month, 1)

        request_data = {
            "period_type": "monthly",
            "period_start": str(first_of_last_month),
            "period_end": str(last_day),
            "project_id": None,
            "force_refresh": False,
        }

        response = client.post(
            profit_generate_url(),
            json=request_data,
            headers=finance_headers,
        )

        # 允许 200 (成功) 或 404 (无数据)
        assert response.status_code in [200, 404], f"Expected 200/404, got {response.status_code}: {response.text}"
        data = response.json()
        assert "success" in data

        if response.status_code == 200:
            assert data["success"] is True
            assert "generated_count" in data["data"]
            assert "period" in data["data"]
            assert "summary" in data["data"]

    def test_get_monthly_profit__returns_200_and_data(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-HP-002: 查询月度利润表 - 返回 200 和数据

        SoT Ref: PROFIT_SOT.md v1.1 §3.3
        """
        today = date.today()
        # 查询上个月
        last_month_date = today - timedelta(days=30)

        response = client.get(
            profit_monthly_url(),
            params={
                "year": last_month_date.year,
                "month": last_month_date.month,
            },
            headers=finance_headers,
        )

        # 允许 200 (有数据) 或 404 (无数据)
        assert response.status_code in [200, 404], f"Expected 200/404, got {response.status_code}: {response.text}"
        data = response.json()
        assert "success" in data

        if response.status_code == 200:
            assert data["success"] is True
            assert "period" in data["data"]
            assert "summary" in data["data"]
            assert "by_project" in data["data"]

    def test_get_daily_profit__returns_200_and_paginated(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-HP-003: 查询日度利润数据 - 返回 200 和分页

        SoT Ref: PROFIT_SOT.md v1.1 §3.4
        """
        today = date.today()
        start_date = today - timedelta(days=7)

        response = client.get(
            profit_daily_url(),
            params={
                "start_date": str(start_date),
                "end_date": str(today),
                "page": 1,
                "page_size": 20,
            },
            headers=finance_headers,
        )

        # 允许 200 (有数据) 或 404 (无数据)
        assert response.status_code in [200, 404], f"Expected 200/404, got {response.status_code}: {response.text}"
        data = response.json()
        assert "success" in data

        if response.status_code == 200:
            assert data["success"] is True
            assert "items" in data["data"]
            assert "total" in data["data"]
            assert "page" in data["data"]

    def test_get_project_profit__returns_200_and_detail(
        self, client, finance_headers, test_project
    ):
        """
        TC-PROFIT-HP-004: 查询项目利润明细 - 返回 200 和明细

        SoT Ref: PROFIT_SOT.md v1.1 §3.5
        """
        today = date.today()
        # 对于月度粒度，开始日期必须是月份的第一天
        start_date = today.replace(day=1) - timedelta(days=30)
        # 确保是月份的第一天
        start_date = start_date.replace(day=1)

        response = client.get(
            profit_project_url(test_project.id),
            params={
                "start_date": str(start_date),
                "end_date": str(today),
                "granularity": "monthly",
            },
            headers=finance_headers,
        )

        # 允许 200 (有数据) 或 404 (无数据/项目不存在)
        assert response.status_code in [200, 404], f"Expected 200/404, got {response.status_code}: {response.text}"
        data = response.json()
        assert "success" in data

        if response.status_code == 200:
            assert data["success"] is True
            assert "project" in data["data"]
            assert "period" in data["data"]
            assert "summary" in data["data"]

    def test_get_account_profit__returns_200_and_detail(
        self, client, finance_headers, test_ad_account
    ):
        """
        TC-PROFIT-HP-005: 查询账户消耗明细 - 返回 200 和明细

        SoT Ref: PROFIT_SOT.md v1.1 §3.6
        """
        today = date.today()
        start_date = today - timedelta(days=30)

        response = client.get(
            profit_account_url(test_ad_account.id),
            params={
                "start_date": str(start_date),
                "end_date": str(today),
            },
            headers=finance_headers,
        )

        # 允许 200 (有数据) 或 404 (无数据/账户不存在)
        assert response.status_code in [200, 404], f"Expected 200/404, got {response.status_code}: {response.text}"
        data = response.json()
        assert "success" in data

        if response.status_code == 200:
            assert data["success"] is True
            assert "account" in data["data"]
            assert "period" in data["data"]
            assert "summary" in data["data"]

    def test_get_profit_summary__returns_200_and_overall(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-HP-006: 查询整体利润汇总 - 返回 200 和汇总

        SoT Ref: PROFIT_SOT.md v1.1 §3.7
        """
        today = date.today()
        last_month_date = today - timedelta(days=30)

        response = client.get(
            profit_summary_url(),
            params={
                "year": last_month_date.year,
                "month": last_month_date.month,
            },
            headers=finance_headers,
        )

        # 允许 200 (有数据) 或 404 (无数据)
        assert response.status_code in [200, 404], f"Expected 200/404, got {response.status_code}: {response.text}"
        data = response.json()
        assert "success" in data

        if response.status_code == 200:
            assert data["success"] is True
            assert "period" in data["data"]
            assert "overall" in data["data"]
            assert "top_projects" in data["data"]


# ============================================================================
# Validation Tests - 参数校验测试
# ============================================================================

@pytest.mark.api
class TestFinanceProfitValidation:
    """
    参数校验测试

    SoT Reference: PROFIT_SOT.md v1.1 §5 (错误码)
    覆盖 BR-PROFIT-005 周期参数校验
    """

    def test_generate_profit__invalid_date_range__returns_400_profit_001(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-VAL-001: period_start > period_end 返回 PROFIT_001

        SoT Ref: PROFIT_SOT.md v1.1 §5.2, BR-PROFIT-005
        """
        request_data = {
            "period_type": "monthly",
            "period_start": "2025-01-31",
            "period_end": "2025-01-01",  # 开始日期 > 结束日期
            "force_refresh": False,
        }

        response = client.post(
            profit_generate_url(),
            json=request_data,
            headers=finance_headers,
        )

        assert response.status_code == 400 or response.status_code == 422
        data = response.json()
        # Pydantic 校验失败或 PROFIT_001
        assert data["success"] is False or "error" in str(data).lower()

    def test_generate_profit__future_start_date__returns_400_profit_002(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-VAL-002: period_start 是未来日期返回 PROFIT_002

        SoT Ref: PROFIT_SOT.md v1.1 §5.2, BR-PROFIT-005
        """
        future_date = date.today() + timedelta(days=30)
        request_data = {
            "period_type": "monthly",
            "period_start": str(future_date),
            "period_end": str(future_date + timedelta(days=30)),
            "force_refresh": False,
        }

        response = client.post(
            profit_generate_url(),
            json=request_data,
            headers=finance_headers,
        )

        assert response.status_code == 400 or response.status_code == 422
        data = response.json()
        assert data["success"] is False or "error" in str(data).lower()

    def test_get_daily_profit__date_range_exceeds_366__returns_400_profit_008(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-VAL-003: 日期范围超 366 天返回 PROFIT_008

        SoT Ref: PROFIT_SOT.md v1.1 §5.2
        """
        today = date.today()
        start_date = today - timedelta(days=400)  # 超过 366 天

        response = client.get(
            profit_daily_url(),
            params={
                "start_date": str(start_date),
                "end_date": str(today),
            },
            headers=finance_headers,
        )

        assert response.status_code == 400 or response.status_code == 422
        data = response.json()
        if response.status_code == 400:
            assert data["success"] is False
            # 检查错误码
            assert "PROFIT_008" in data.get("code", "") or "range" in data.get("message", "").lower()


# ============================================================================
# Permission Tests - 权限验证测试
# ============================================================================

@pytest.mark.api
class TestFinanceProfitPermission:
    """
    权限验证测试

    SoT Reference: PROFIT_SOT.md v1.1 §3 (权限矩阵)
    """

    def test_generate_profit__media_buyer__returns_403(
        self, client, media_buyer_headers
    ):
        """
        TC-PROFIT-PERM-001: media_buyer 无权生成聚合 - 返回 403

        SoT Ref: PROFIT_SOT.md v1.1 §3.2 (仅 admin/finance)
        """
        request_data = {
            "period_type": "monthly",
            "period_start": "2025-01-01",
            "period_end": "2025-01-31",
        }

        response = client.post(
            profit_generate_url(),
            json=request_data,
            headers=media_buyer_headers,
        )

        assert response.status_code == 403
        data = response.json()
        assert data["success"] is False or "code" in data

    def test_get_monthly_profit__media_buyer__returns_403(
        self, client, media_buyer_headers
    ):
        """
        TC-PROFIT-PERM-002: media_buyer 无权查看月度汇总 - 返回 403

        SoT Ref: PROFIT_SOT.md v1.1 §3.3 (仅 admin/finance)
        """
        response = client.get(
            profit_monthly_url(),
            params={"year": 2025, "month": 1},
            headers=media_buyer_headers,
        )

        assert response.status_code == 403

    def test_get_profit_summary__media_buyer__returns_403(
        self, client, media_buyer_headers
    ):
        """
        TC-PROFIT-PERM-003: media_buyer 无权查看整体汇总 - 返回 403

        SoT Ref: PROFIT_SOT.md v1.1 §3.7 (仅 admin/finance)
        """
        response = client.get(
            profit_summary_url(),
            params={"year": 2025, "month": 1},
            headers=media_buyer_headers,
        )

        assert response.status_code == 403

    def test_force_refresh__finance_user__returns_403(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-PERM-004: finance 用户无权强制刷新 - 返回 403

        SoT Ref: PROFIT_SOT.md v1.1 §3.2, BR-PROFIT-004
        """
        request_data = {
            "period_type": "monthly",
            "period_start": "2025-01-01",
            "period_end": "2025-01-31",
            "force_refresh": True,  # 仅 admin 可用
        }

        response = client.post(
            profit_generate_url(),
            json=request_data,
            headers=finance_headers,
        )

        assert response.status_code == 403
        data = response.json()
        assert data["success"] is False


# ============================================================================
# Error Code Tests - 错误码测试
# ============================================================================

@pytest.mark.api
class TestFinanceProfitErrorCodes:
    """
    错误码测试

    SoT Reference: PROFIT_SOT.md v1.1 §5
    覆盖 PROFIT_001 ~ PROFIT_008
    """

    def test_get_project_profit__project_not_found__returns_404_profit_003(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-ERR-001: 项目不存在返回 PROFIT_003

        SoT Ref: PROFIT_SOT.md v1.1 §5.2
        """
        non_existent_project_id = 999999

        response = client.get(
            profit_project_url(non_existent_project_id),
            params={
                "start_date": "2025-01-01",
                "end_date": "2025-01-31",
            },
            headers=finance_headers,
        )

        assert response.status_code == 404
        data = response.json()
        assert data["success"] is False
        assert "PROFIT_003" in data.get("code", "")

    def test_get_account_profit__account_not_found__returns_404_profit_007(
        self, client, finance_headers
    ):
        """
        TC-PROFIT-ERR-002: 账户不存在返回 PROFIT_007

        SoT Ref: PROFIT_SOT.md v1.1 §5.2
        """
        non_existent_account_id = 999999

        response = client.get(
            profit_account_url(non_existent_account_id),
            params={
                "start_date": "2025-01-01",
                "end_date": "2025-01-31",
            },
            headers=finance_headers,
        )

        assert response.status_code == 404
        data = response.json()
        assert data["success"] is False
        assert "PROFIT_007" in data.get("code", "")


# ============================================================================
# Fixtures - 使用 conftest.py 中已定义的 fixtures
# ============================================================================
#
# 本测试文件使用以下来自 conftest.py 的 fixtures：
# - client: TestClient
# - finance_headers: finance 角色的 Authorization 头
# - media_buyer_headers: media_buyer 角色的 Authorization 头
# - test_project: 测试用项目
# - test_ad_account: 测试用广告账户
# - db_session: SQLAlchemy Session
#


# ============================================================================
# Notes
# ============================================================================
"""
测试覆盖矩阵 (PROFIT_SOT.md v1.1 §6.2):

| test_id | 场景 | 状态 |
|---------|-----|------|
| TC-PROFIT-HP-001 | 生成月度聚合成功 | ✅ |
| TC-PROFIT-HP-002 | 查询月度利润表 | ✅ |
| TC-PROFIT-HP-003 | 查询日度利润数据 | ✅ |
| TC-PROFIT-HP-004 | 查询项目利润明细 | ✅ |
| TC-PROFIT-HP-005 | 查询账户消耗明细 | ✅ |
| TC-PROFIT-HP-006 | 查询整体汇总 | ✅ |
| TC-PROFIT-VAL-001 | period_start > period_end | ✅ |
| TC-PROFIT-VAL-002 | period_start 是未来日期 | ✅ |
| TC-PROFIT-VAL-003 | 日期范围超 366 天 | ✅ |
| TC-PROFIT-PERM-001 | media_buyer 无权生成 | ✅ |
| TC-PROFIT-PERM-002 | media_buyer 无权查月度 | ✅ |
| TC-PROFIT-PERM-003 | media_buyer 无权查汇总 | ✅ |
| TC-PROFIT-PERM-004 | finance 无权强制刷新 | ✅ |
| TC-PROFIT-ERR-001 | 项目不存在 PROFIT_003 | ✅ |
| TC-PROFIT-ERR-002 | 账户不存在 PROFIT_007 | ✅ |

依赖 fixtures (来自 conftest.py):
- client: TestClient
- finance_headers: finance 角色的 Authorization 头
- media_buyer_headers: media_buyer 角色的 Authorization 头
- test_project: 测试用项目 (已修复: sample_project → test_project)
- test_ad_account: 测试用广告账户 (已修复: sample_ad_account → test_ad_account)
- db_session: SQLAlchemy Session
"""
